# Generated by Django 4.2.30 on 2026-07-14 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('smoking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('exercise', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10)),
                ('alcohol', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('family_history', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('bmi', models.FloatField()),
                ('blood_pressure', models.CharField(help_text='Blood Pressure in mmHg (e.g., 120/80)', max_length=7)),
                ('cholesterol', models.FloatField(help_text='Cholesterol in mg/dL')),
                ('glucose', models.FloatField(help_text='Glucose in mg/dL')),
                ('sleep', models.FloatField(help_text='hours per day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
