# Generated by Django 4.2.30 on 2026-08-04 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=10)),
                ('race', models.CharField(choices=[('AfricanAmerican', 'African American'), ('Asian', 'Asian'), ('Caucasian', 'Caucasian'), ('Hispanic', 'Hispanic'), ('Other', 'Other')], max_length=20)),
                ('hypertension', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('bmi', models.FloatField()),
                ('hbA1c_level', models.FloatField(help_text='HbA1c percentage')),
                ('blood_glucose_level', models.FloatField(help_text='Blood glucose level')),
                ('smoking_history', models.CharField(choices=[('No Info', 'No Info'), ('current', 'Current'), ('ever', 'Ever'), ('former', 'Former'), ('never', 'Never'), ('not current', 'Not Current')], max_length=20)),
                ('diabetes_prediction', models.CharField(blank=True, max_length=50, null=True)),
                ('diabetes_confidence', models.FloatField(blank=True, null=True)),
                ('diabetic_probability', models.FloatField(default=0)),
                ('non_diabetic_probability', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
