# Generated by Django 4.2.30 on 2026-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='blood_glucose_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='hbA1c_level',
            field=models.FloatField(verbose_name='HbA1c Level'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='heart_disease',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='hypertension',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
