# Generated by Django 4.2.30 on 2026-08-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_healthrecord_blood_glucose_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='heart_disease',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='hypertension',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
    ]
