# Generated by Django 4.2.30 on 2026-07-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_healthrecord_diabetes_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='diabetes_pedigree_function',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='insulin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='pregnancies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='skin_thickness',
            field=models.FloatField(default=0.0),
        ),
    ]
