# Generated by Django 4.2.30 on 2026-08-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_healthrecord_heart_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='heart_disease',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='hypertension',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True),
        ),
    ]
