# Generated by Django 4.2.30 on 2026-08-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_healthrecord_diabetes_pedigree_function_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='diabetic_probability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='non_diabetic_probability',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='blood_pressure',
            field=models.CharField(help_text='Example: 120/80', max_length=7),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='cholesterol',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='glucose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='sleep',
            field=models.FloatField(help_text='Hours per day'),
        ),
    ]
