# Generated by Django 4.2.30 on 2026-08-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_healthrecord_diabetic_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='blood_pressure',
            field=models.CharField(help_text='Systolic blood pressure in mmHg', max_length=7),
        ),
    ]
