# Generated by Django 5.2.17 on 2026-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_healthrecord_heart_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='heart_disease',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='hypertension',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
