# Generated by Django 4.2.30 on 2026-08-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_healthrecord_blood_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='blood_pressure',
            field=models.IntegerField(help_text='Systolic blood pressure in mmHg'),
        ),
    ]
